### ISSUE TITLE
設定画面のUI作成

### ISSUE THREAD

**Issue by SEKI-YUTA** [GEEKCAMP-Vol12/GEEKCAMP_Vol.12#13]
figma
https://www.figma.com/design/phXe3FkxWuLVzNMNYwBFVy/%E7%94%BB%E9%9D%A2%E8%A8%AD%E8%A8%88?node-id=0-1&t=zv4jI5OOt6hzXHBg-0

**Comment by honoka5** [comment]
figma通りのボタンじゃなくてなんかボタン追加して押すにみたいになりそう💦

**Comment by honoka5** [comment]
頑張ってしばらくデザイン通りの牡丹探します…

**Comment by honoka5** [comment]
![スクリーンショット 2024-08-07 154709](https://github.com/user-attachments/assets/341be11c-1d38-4d25-81e6-b8fbe443c5c3)
こんなのになって動けないので再起動かけます

**Comment by honoka5** [comment]
何回やっても真っ黒でした（‘＿‘）

**Comment by honoka5** [comment]
原因が分かりません

**Comment by honoka5** [comment]
設定画面完成いえいいえい
