### ISSUE TITLE
睡眠時間やカフェイン摂取量を踏まえた健康ポイントの計算式を考える

### ISSUE THREAD

**Issue by SEKI-YUTA** [GEEKCAMP-Vol12/GEEKCAMP_Vol.12#17]
睡眠時間やカフェイン摂取量を踏まえたポイントによってホーム画面の表示を変えたいので、そのポイントを求める計算を考えて欲しいです。
ある程度根拠がある計算式の方がいい

**Comment by HYO-KM** [comment]
### 不健康ポイントの計算

**睡眠不足のポイント計算**

 成人(25歳ぐらい)の睡眠時間の中で最も死亡率の低い時間が7時間

**{7-X(睡眠時間)}＊100= Y(不健康ポイント)**

(例)ユーザーが3時間しか寝ていない場合
(7-3)＊100= 400pts

**カフェイン摂取量のポイント計算**

成人の1日のカフェイン摂取量は400mgが上限
**{A(カフェイン摂取量) >= 400 の場合}
A-400= B(不健康ポイント)** 


(例)ユーザーの1日のカフェイン摂取量が500mgの場合
500-400= 100pts

**上記の2要素を足し合わせる**
400+100= 500pts

**Comment by HYO-KM** [comment]
**7時間 → 420分 に変更**
分で計算できるようにしました
(追記)カフェイン量：コーヒー１杯（150ml）当たり約90mg

睡眠不足ポイント
420-X(分)= Y(不健康ポイント)

(例1)睡眠時間6h0m,カフェイン摂取量450mgの場合
420 - 6(時) ＊ 60 - 0(分) =  60
450(mg) - 400 = 50
60 + 50 = 110(ポイント)

(例2)睡眠時間5h30m,カフェイン摂取量400mgの場合
420 - 5(時) ＊ 60 - 30(分) = 90  
400(mg) - 400 = 0
90 + 0 = 90(ポイント)

(例3)睡眠時間8h0m,カフェイン摂取量300mgの場合
睡眠時間 > 420(分) , カフェイン摂取量 < 400(mg) なので
0(ポイント)

**Comment by SEKI-YUTA** [comment]
現状キャラの画像が４枚あるんだけど、

0\~50　一番元気ある画像
51\~100 普通の画像
101\~150 元気ない画像
151以上　寝込んでる画像
みたいな感じになるのかな？
画像の出しわけが

**Comment by HYO-KM** [comment]
画像を1日の記録ごとに変化させる場合だったら、このくらいでいいと思います。
この場合、前日で不健康ポイントが151以上で寝込んでいる画像だったが、その次の日は不健康ポイントが0で一番元気のある画像に変化することになりますね。

例えば、1週間前からの記録の合計を画像に反映させる場合でも基準値的には 7倍 にするだけでいいと思います。

**Comment by SEKI-YUTA** [comment]
確かに1日単位にするのいきなり変化しすぎる気がするから1週間とかにしようか。
1週間分とかで評価したいから、一旦今週のデータを取って平均を出してから×７すると1週間分のデータを出せそう。一旦平均出すことによってデータが7つなくても1週間換算にできる。
